import type { Track } from "@/types/dj";

export const MOCK_TRACKS: Track[] = [
  {
    id: 1,
    title: "Midnight Drive",
    artist: "Luna Wave",
    bpm: 124,
    key: "Am",
    genre: "House",
    energy: 6,
    tags: ["warmup", "groove"],
    notes: "Smooth opener",
  },
  {
    id: 2,
    title: "Neon Pulse",
    artist: "Chrome City",
    bpm: 128,
    key: "Fm",
    genre: "Techno",
    energy: 8,
    tags: ["peak", "driving"],
    notes: null,
  },
  {
    id: 3,
    title: "Velvet Floor",
    artist: "DJ Sable",
    bpm: 122,
    key: "Dm",
    genre: "Deep House",
    energy: 5,
    tags: ["warmup", "vocal"],
    notes: "Acapella-friendly outro",
  },
  {
    id: 4,
    title: "Riser Protocol",
    artist: "Static Bloom",
    bpm: 132,
    key: "Gm",
    genre: "Techno",
    energy: 9,
    tags: ["peak", "tool"],
    notes: "16-bar breakdown",
  },
  {
    id: 5,
    title: "Sunset Relay",
    artist: "Harbor Light",
    bpm: 126,
    key: "Cm",
    genre: "Melodic House",
    energy: 7,
    tags: ["melodic", "emotional"],
    notes: null,
  },
  {
    id: 6,
    title: "Basement Signal",
    artist: "Low Unit",
    bpm: 130,
    key: "Em",
    genre: "Tech House",
    energy: 8,
    tags: ["groove", "peak"],
    notes: "Works well after 128 BPM records",
  },
  {
    id: 7,
    title: "Glass Garden",
    artist: "Mira Kline",
    bpm: 120,
    key: "Bm",
    genre: "Organic House",
    energy: 4,
    tags: ["warmup", "organic"],
    notes: null,
  },
  {
    id: 8,
    title: "Afterglow",
    artist: "North Arcade",
    bpm: 118,
    key: "Am",
    genre: "Downtempo",
    energy: 3,
    tags: ["closing", "chill"],
    notes: "Good last track",
  },
  {
    id: 9,
    title: "Voltage Bloom",
    artist: "Phase Nine",
    bpm: 134,
    key: "F#m",
    genre: "Techno",
    energy: 10,
    tags: ["peak", "hard"],
    notes: null,
  },
  {
    id: 10,
    title: "Paper Moon",
    artist: "Echo Park",
    bpm: 125,
    key: "Dm",
    genre: "House",
    energy: 6,
    tags: ["vocal", "classic"],
    notes: "Crowd favorite",
  },
  {
    id: 11,
    title: "Drift Channel",
    artist: "Sub Atlas",
    bpm: 128,
    key: "Am",
    genre: "Progressive House",
    energy: 7,
    tags: ["progressive", "long mix"],
    notes: null,
  },
  {
    id: 12,
    title: "Quiet Storm",
    artist: "Grey Lantern",
    bpm: 115,
    key: "Gm",
    genre: "Ambient",
    energy: 2,
    tags: ["closing", "ambient"],
    notes: "Fade-friendly",
  },
];

export const ALL_KEYS = [
  ...new Set(
    MOCK_TRACKS.map((t) => t.key).filter((k): k is string => k !== null),
  ),
].sort();

export const ALL_TAGS = [
  ...new Set(MOCK_TRACKS.flatMap((t) => t.tags)),
].sort();
